spring:
  application:
    name: sso-client-2

  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: sso-client-2
            client-secret: CuRYID5HNS9XKWDLuekmCVXkjRpmeSNV
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9001/sso-client-2/*
        provider:
          custom:
            authorization-uri: http://localhost:9081/realms/master/protocol/openid-connect/auth
            token-uri: http://localhost:9081/realms/master/protocol/openid-connect/token
            user-info-uri: http://localhost:9081/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:9081/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username

  thymeleaf:
    cache: false
  cache:
    type: NONE

server:
  port: 9001
  servlet:
    context-path: /sso-client-2

logging:
  level:
    org.springframework: INFO