spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: auth-client-1
            client-secret: JcABkUe9OcxbQiukVdb1TxLkECuVB3Nx
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:9081/realms/spring-boot-code/protocol/openid-connect/auth
            token-uri: http://localhost:9081/realms/spring-boot-code/protocol/openid-connect/token
            user-info-uri: http://localhost:9081/realms/spring-boot-code/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:9081/realms/spring-boot-code/protocol/openid-connect/certs
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet:
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8081/sso-resource-server/api/foos/
              
keycloak:
  realm: spring-boot-code
  domain: localhost:9081
  adminClientId: master-client
  adminClientSecret: nI2KfcrIqj6KWVfLqPMSEUoLHjvPtobo
  client: auth-client-1
  urls:
    auth: http://${keycloak.domain}