spring:
  application:
    name: sso-client-1

  thymeleaf:
    cache: false
  cache:
    type: NONE

#  security:
#    oauth2:
#      client:
#        registration:
#          custom:
#            client-id: ssoClient-2
#            client-secret: ssoClientSecret-2
#            scope: read,write,openid
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:9000/sso-client-1/login/oauth2/code/custom
#        provider:
#          custom:
#            authorization-uri: http://localhost:9081/realms/auth-client-1/protocol/openid-connect/auth
#            token-uri: http://localhost:9081/realms/auth-client-1/protocol/openid-connect/token
#            user-info-uri: http://localhost:9081/realms/auth-client-1/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:9081/realms/auth-client-1/protocol/openid-connect/certs
#            user-name-attribute: preferred_username

server:
  port: 9000
  servlet:
    context-path: /sso-client-1

logging:
  level:
    org.springframework: INFO

keycloak:
  realm: master
  domain: localhost:9081
  adminClientId: admin-cli
  adminClientSecret: TW5BhUcNK5PbRM0TozfD9CySrxwLbGAG
  client: authenticationClientId
  username: admin
  password: admin@1234
  tokenURL: http://localhost:9081/realms/master/protocol/openid-connect/token
  createUserURL: http://${keycloak.domain}/admin/realms/master/users
  urls:
    auth: http://${keycloak.domain}